name: Deploy to EC2



on:

  push:

    branches:

      - master



jobs:

  deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Run tests

        run: npm test



      - name: Copy files to EC2

        uses: appleboy/scp-action@v0.1.7

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.PRIVATE_KEY }}

          source: "."

          target: "~/app"



      - name: SSH and restart app

        uses: appleboy/ssh-action@v1.0.0

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.PRIVATE_KEY }}

          script: |

            cd ~/app

            npm install

            pm2 stop all || true

            pm2 start index.js --name projekt-java || pm2 restart projekt-java

